Repository takuma-ru/Fascino, pull requests merged in 2021-12, with the labels that each got.

#32 [WIP] Feature/storage
  store/storage.js
Labels: enhancement

#4 feature/realtime
  store/rtdb.js
Labels: enhancement, help wanted

#28 feature/postInfoModal
  components/BottomNaviBar.vue
  components/PostInfoModal.vue
Labels: enhancement

#33 update/auth
  store/auth.js
Labels: update

#34 update/common
  assets/icomoon/demo-files/demo.css
  assets/icomoon/demo.html
  assets/icomoon/fonts/icomoon.eot
  assets/icomoon/fonts/icomoon.svg
  assets/icomoon/fonts/icomoon.ttf
  assets/icomoon/fonts/icomoon.woff
  assets/icomoon/selection.json
  assets/icomoon/style.css
  assets/loadingIndicator.html
  components/BottomNaviBar.vue
  nuxt.config.js
  pages/index.vue
Labels: update

#42 update/common
  assets/loadingIndicator.html
  components/Button.vue
  layouts/error.vue
  nuxt.config.js
  static/screenshots/screenshot_01.png
  static/screenshots/screenshot_02.png
  static/screenshots/screenshot_03.png
Labels: bug, update

#43 update/common
  components/Button.vue
  nuxt.config.js
Labels: update

#2 [WIP] feature/account
  pages/account/_uid.vue
Labels: enhancement

#6 [WIP] Feature/map
  components/SpotMarkerAndModal.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/map.vue
  static/icon/map-marker.svg
  store/firestore.js
Labels: enhancement

#41 [WIP] update/postInfoModal
  components/PostInfoModal.vue
Labels: update

#30 feature/postModal
  assets/variables.scss
  components/PostModal.vue
  package-lock.json
  package.json
  static/icon/map-marker-star.svg
  static/icon/target.svg
  static/image/notFound.svg
Labels: enhancement

#35 [WIP] feature/index
  assets/title.svg
  components/PWAInstallButton.vue
  pages/index.vue
Labels: enhancement

#47 feature/geolocation
  nuxt.config.js
  package-lock.json
  package.json
  store/geolocation.js
Labels: enhancement

#48 Update/postInfoModal
  components/PostInfoModal.vue
Labels: bug, update
