Repository takuma-ru/Fascino, pull requests merged in 2022-01, with the labels that each got.

#49 [WIP] update/index + feature/siginIn + update/common
  assets/fascino_title.svg
  assets/fascino_title_dark.svg
  assets/fascino_title_logo.svg
  assets/fascino_title_logo_dark.svg
  assets/title.svg
  components/BottomNaviBar.vue
  components/PWAInstallButton.vue
  components/SignInButton.vue
  layouts/default.vue
  nuxt.config.js
  pages/index.vue
  pages/signin.vue
  pages/signup.vue
  store/auth.js
Labels: enhancement, update

#55 feature/snackbar
  components/Snackbars.vue
  layouts/default.vue
  store/snackbar.js
Labels: enhancement

#50 [WIP]update/postModal
  components/PostModal.vue
Labels: update

#62 Update/postInfoModal
  components/PostInfoModal.vue
Labels: bug, update

#67 update/storage
  package-lock.json
  package.json
  store/storage.js
Labels: bug, update

#68 [WIP] update/serviceWorker
  components/BottomNaviBar.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
Labels: bug, update
